// Copyright 2022, the Chromium project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }


  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyB5klb6cyMOCKPemp8cAIAvMibjbTqEUuk",
    authDomain: "kirk-9aadd.firebaseapp.com",
    projectId: "kirk-9aadd",
    storageBucket: "kirk-9aadd.appspot.com",
    messagingSenderId: "140101484711",
    appId: "1:140101484711:web:e85b360ded6fc356755b82",
    measurementId: "G-QEDT486EGC",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDm9TDFnOYB4wd4vnwsM7OVWK3jTRS5-Hg',
    appId: '1:140101484711:android:3507b18c112a929f755b82',
    messagingSenderId: '140101484711',
    projectId: 'kirk-9aadd',
    storageBucket: 'kirk-9aadd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5klb6cyMOCKPemp8cAIAvMibjbTqEUuk',
    appId: '1:140101484711:web:e85b360ded6fc356755b82',
    messagingSenderId: '140101484711',
    projectId: 'kirk-9aadd',
    storageBucket: 'kirk-9aadd.appspot.com',
    authDomain: "kirk-9aadd.firebaseapp.com",
    measurementId: "G-QEDT486EGC",
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5klb6cyMOCKPemp8cAIAvMibjbTqEUuk',
    appId: '1:140101484711:web:e85b360ded6fc356755b82',
    messagingSenderId: '140101484711',
    projectId: 'kirk-9aadd',
    storageBucket: 'kirk-9aadd.appspot.com',
    authDomain: "kirk-9aadd.firebaseapp.com",
    measurementId: "G-QEDT486EGC",
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5klb6cyMOCKPemp8cAIAvMibjbTqEUuk',
    appId: '1:140101484711:web:e85b360ded6fc356755b82',
    messagingSenderId: '140101484711',
    projectId: 'kirk-9aadd',
    storageBucket: 'kirk-9aadd.appspot.com',
    authDomain: "kirk-9aadd.firebaseapp.com",
    measurementId: "G-QEDT486EGC",
  );
}